"""b2b quotes, industries, blog and GST order fields

Revision ID: 749aef5be6f3
Revises: 0003_coupon_value_constraint
Created: 2026-09-27 14:01:09.941009
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '749aef5be6f3'
down_revision: str | None = '0003_coupon_value_constraint'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_categories',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('seo_title', sa.String(length=180), nullable=True),
    sa.Column('seo_description', sa.String(length=320), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_categories')),
    sa.UniqueConstraint('slug', name='uq_blog_categories_slug')
    )
    op.create_table('industries',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('tagline', sa.String(length=240), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('hero_image_url', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=48), nullable=True, comment="lucide icon name, e.g. 'factory'"),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('seo_title', sa.String(length=180), nullable=True),
    sa.Column('seo_description', sa.String(length=320), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_industries')),
    sa.UniqueConstraint('slug', name='uq_industries_slug')
    )
    op.create_index('ix_industries_is_active_position', 'industries', ['is_active', 'position'], unique=False)
    op.create_table('blog_posts',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('excerpt', sa.String(length=400), nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('cover_image_alt', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='DRAFT', nullable=False),
    sa.Column('author_name', sa.String(length=120), nullable=True),
    sa.Column('author_profile_id', sa.UUID(), nullable=True),
    sa.Column('reading_minutes', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('compliance_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seo_title', sa.String(length=180), nullable=True),
    sa.Column('seo_description', sa.String(length=320), nullable=True),
    sa.Column('faq', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(excerpt) BETWEEN 1 AND 400', name=op.f('ck_blog_posts_excerpt_length')),
    sa.CheckConstraint('char_length(title) BETWEEN 1 AND 200', name=op.f('ck_blog_posts_title_length')),
    sa.ForeignKeyConstraint(['author_profile_id'], ['profiles.id'], name=op.f('fk_blog_posts_author_profile_id_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_posts')),
    sa.UniqueConstraint('slug', name='uq_blog_posts_slug')
    )
    op.create_index('ix_blog_posts_published_at', 'blog_posts', ['published_at'], unique=False)
    op.create_index('ix_blog_posts_status_published', 'blog_posts', ['status', 'published_at'], unique=False)
    op.create_table('contact_messages',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=24), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source_page', sa.String(length=240), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('handled_by_profile_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('char_length(body) BETWEEN 1 AND 4000', name=op.f('ck_contact_messages_body_length')),
    sa.ForeignKeyConstraint(['handled_by_profile_id'], ['profiles.id'], name=op.f('fk_contact_messages_handled_by_profile_id_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_messages'))
    )
    op.create_index('ix_contact_messages_is_read', 'contact_messages', ['is_read'], unique=False)
    op.create_table('blog_post_categories',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['blog_categories.id'], name=op.f('fk_blog_post_categories_category_id_blog_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], name=op.f('fk_blog_post_categories_post_id_blog_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'category_id', name=op.f('pk_blog_post_categories'))
    )
    op.create_index('ix_blog_post_categories_category_id', 'blog_post_categories', ['category_id'], unique=False)
    op.create_table('blog_post_products',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], name=op.f('fk_blog_post_products_post_id_blog_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_blog_post_products_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'product_id', name=op.f('pk_blog_post_products'))
    )
    op.create_index('ix_blog_post_products_post_position', 'blog_post_products', ['post_id', 'position'], unique=False)
    op.create_table('industry_products',
    sa.Column('industry_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.String(length=240), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], name=op.f('fk_industry_products_industry_id_industries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_industry_products_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('industry_id', 'product_id', name=op.f('pk_industry_products'))
    )
    op.create_index('ix_industry_products_industry_position', 'industry_products', ['industry_id', 'position'], unique=False)
    op.create_table('product_views',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('session_key', sa.String(length=64), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('view_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_views_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_product_views_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_views'))
    )
    op.create_index('ix_product_views_product_id', 'product_views', ['product_id'], unique=False)
    op.create_index('ix_product_views_session_recent', 'product_views', ['session_key', 'viewed_at'], unique=False)
    op.create_table('quote_requests',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=24), nullable=False),
    sa.Column('city', sa.String(length=96), nullable=True),
    sa.Column('state', sa.String(length=96), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=True, comment='Snapshot, so the request survives product deletion'),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('preferred_material', sa.String(length=64), nullable=True),
    sa.Column('preferred_size', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'QUOTED', 'CONVERTED', 'CLOSED', name='quote_status'), server_default='NEW', nullable=False),
    sa.Column('assigned_to_profile_id', sa.UUID(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('quoted_amount', sa.Integer(), nullable=True, comment='Minor units (paise)'),
    sa.Column('quoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('converted_order_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=24), nullable=False, comment='Human readable, e.g. QT-8F3A2C'),
    sa.Column('source', sa.String(length=48), nullable=True, comment='product_page | bulk_order | contact'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gstin IS NULL OR gstin ~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]Z[0-9A-Z]$'", name=op.f('ck_quote_requests_gstin_format')),
    sa.CheckConstraint('quantity IS NULL OR quantity > 0', name=op.f('ck_quote_requests_quantity_positive')),
    sa.ForeignKeyConstraint(['assigned_to_profile_id'], ['profiles.id'], name=op.f('fk_quote_requests_assigned_to_profile_id_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['converted_order_id'], ['orders.id'], name=op.f('fk_quote_requests_converted_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_quote_requests_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_quote_requests_variant_id_product_variants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_requests')),
    sa.UniqueConstraint('reference', name=op.f('uq_quote_requests_reference'))
    )
    op.create_index('ix_quote_requests_assigned', 'quote_requests', ['assigned_to_profile_id', 'status'], unique=False)
    op.create_index('ix_quote_requests_status_created', 'quote_requests', ['status', 'created_at'], unique=False)
    op.create_index('uq_quote_requests_open_per_email', 'quote_requests', ['email', 'product_id'], unique=True, postgresql_where=sa.text("status = 'NEW'"))
    op.add_column('orders', sa.Column('is_business_order', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('orders', sa.Column('company_name', sa.String(length=200), nullable=True))
    op.add_column('orders', sa.Column('gstin', sa.String(length=15), nullable=True))
    op.add_column('orders', sa.Column('purchase_order_number', sa.String(length=64), nullable=True))
    op.add_column('orders', sa.Column('taxable_amount', sa.Integer(), server_default='0', nullable=False, comment='Minor units. subtotal - discount_total, shipping excluded.'))
    op.add_column('orders', sa.Column('tax_rate_bps', sa.Integer(), server_default='1800', nullable=False))
    op.add_column('orders', sa.Column('tax_inclusive', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('orders', sa.Column('hsn_code', sa.String(length=12), nullable=True))
    op.add_column('orders', sa.Column('invoice_number', sa.String(length=40), nullable=True))
    op.add_column('orders', sa.Column('invoice_issued_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(op.f('uq_orders_invoice_number'), 'orders', ['invoice_number'])
    op.create_index('ix_product_variants_attributes_gin', 'product_variants', ['attributes'], unique=False, postgresql_using='gin', postgresql_ops={'attributes': 'jsonb_path_ops'})
    op.create_index('ix_product_variants_material', 'product_variants', [sa.literal_column("(attributes ->> 'Material')")], unique=False)
    op.create_index('ix_product_variants_material_size', 'product_variants', [sa.literal_column("(attributes ->> 'Material')"), sa.literal_column("(attributes ->> 'Size')")], unique=False)
    op.create_index('ix_product_variants_size', 'product_variants', [sa.literal_column("(attributes ->> 'Size')")], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_variants_size', table_name='product_variants')
    op.drop_index('ix_product_variants_material_size', table_name='product_variants')
    op.drop_index('ix_product_variants_material', table_name='product_variants')
    op.drop_index('ix_product_variants_attributes_gin', table_name='product_variants', postgresql_using='gin', postgresql_ops={'attributes': 'jsonb_path_ops'})
    op.drop_constraint(op.f('uq_orders_invoice_number'), 'orders', type_='unique')
    op.drop_column('orders', 'invoice_issued_at')
    op.drop_column('orders', 'invoice_number')
    op.drop_column('orders', 'hsn_code')
    op.drop_column('orders', 'tax_inclusive')
    op.drop_column('orders', 'tax_rate_bps')
    op.drop_column('orders', 'taxable_amount')
    op.drop_column('orders', 'purchase_order_number')
    op.drop_column('orders', 'gstin')
    op.drop_column('orders', 'company_name')
    op.drop_column('orders', 'is_business_order')
    op.drop_index('uq_quote_requests_open_per_email', table_name='quote_requests', postgresql_where=sa.text("status = 'NEW'"))
    op.drop_index('ix_quote_requests_status_created', table_name='quote_requests')
    op.drop_index('ix_quote_requests_assigned', table_name='quote_requests')
    op.drop_table('quote_requests')
    op.drop_index('ix_product_views_session_recent', table_name='product_views')
    op.drop_index('ix_product_views_product_id', table_name='product_views')
    op.drop_table('product_views')
    op.drop_index('ix_industry_products_industry_position', table_name='industry_products')
    op.drop_table('industry_products')
    op.drop_index('ix_blog_post_products_post_position', table_name='blog_post_products')
    op.drop_table('blog_post_products')
    op.drop_index('ix_blog_post_categories_category_id', table_name='blog_post_categories')
    op.drop_table('blog_post_categories')
    op.drop_index('ix_contact_messages_is_read', table_name='contact_messages')
    op.drop_table('contact_messages')
    op.drop_index('ix_blog_posts_status_published', table_name='blog_posts')
    op.drop_index('ix_blog_posts_published_at', table_name='blog_posts')
    op.drop_table('blog_posts')
    op.drop_index('ix_industries_is_active_position', table_name='industries')
    op.drop_table('industries')
    op.drop_table('blog_categories')
    # ### end Alembic commands ###
