"""initial schema

Revision ID: f93d8a27effa
Revises: 0000_extensions
Created: 2026-09-27 13:24:52.223466
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'f93d8a27effa'
down_revision: str | None = '0000_extensions'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#: Native enum types created inline by the table definitions above, in an order
#: that is safe to drop once every table is gone.
_ENUM_TYPES = (
    'inventory_reason',
    'outbox_status',
    'email_kind',
    'discount_source',
    'refund_status',
    'payment_status',
    'payment_provider',
    'order_status',
    'order_shipping_method',
    'coupon_type',
    'cart_status',
    'address_type',
    'review_status',
    'subscriber_status',
    'shipping_method_code',
    'variant_status',
    'product_status',
    'user_role',
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_daily',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('day', sa.DateTime(timezone=True), nullable=False),
    sa.Column('orders_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('items_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('gross_revenue', sa.Integer(), server_default='0', nullable=False),
    sa.Column('discount_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tax_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('shipping_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('refunded_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('new_customers', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_daily')),
    sa.UniqueConstraint('day', name='uq_analytics_daily_day')
    )
    op.create_table('categories',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('path', sa.Text(), server_default='', nullable=False),
    sa.Column('position', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('seo_title', sa.String(length=180), nullable=True),
    sa.Column('seo_description', sa.String(length=320), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('slug', name='uq_categories_slug')
    )
    op.create_index('ix_categories_is_active_position', 'categories', ['is_active', 'position'], unique=False)
    op.create_index('ix_categories_parent_id', 'categories', ['parent_id'], unique=False)
    op.create_table('id_counters',
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('value', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_id_counters'))
    )
    op.create_table('idempotency_keys',
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), server_default=sa.text("now() + interval '48 hours'"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_keys'))
    )
    op.create_index('ix_idempotency_keys_expires_at', 'idempotency_keys', ['expires_at'], unique=False)
    op.create_index('uq_idempotency_keys_scope_key', 'idempotency_keys', ['scope', 'key'], unique=True)
    op.create_table('outbox_events',
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SENT', 'FAILED', name='outbox_status'), server_default='PENDING', nullable=False),
    sa.Column('dedupe_key', sa.String(length=160), nullable=True),
    sa.Column('attempts', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events'))
    )
    op.create_index('ix_outbox_events_dedupe_key', 'outbox_events', ['dedupe_key'], unique=True)
    op.create_index('ix_outbox_events_status_created', 'outbox_events', ['status', 'created_at'], unique=False)
    op.create_table('profiles',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=24), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('CUSTOMER', 'ADMIN', name='user_role'), server_default='CUSTOMER', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marketing_opt_in', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles')),
    sa.UniqueConstraint('email', name='uq_profiles_email')
    )
    op.create_index('ix_profiles_created_at', 'profiles', ['created_at'], unique=False)
    op.create_index('ix_profiles_role', 'profiles', ['role'], unique=False)
    op.create_table('shipping_methods',
    sa.Column('code', sa.Enum('STANDARD', 'EXPRESS', name='shipping_method_code'), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Integer(), server_default='0', nullable=False),
    sa.Column('free_above', sa.Integer(), nullable=True),
    sa.Column('estimated_days_min', sa.SmallInteger(), server_default='3', nullable=False),
    sa.Column('estimated_days_max', sa.SmallInteger(), server_default='5', nullable=False),
    sa.Column('handling_fee', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('position', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price >= 0', name=op.f('ck_shipping_methods_price_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipping_methods')),
    sa.UniqueConstraint('code', name='uq_shipping_methods_code')
    )
    op.create_table('tags',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('slug', name='uq_tags_slug')
    )
    op.create_table('webhook_events',
    sa.Column('provider', sa.String(length=32), server_default='razorpay', nullable=False),
    sa.Column('provider_event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.String(length=256), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events'))
    )
    op.create_index('ix_webhook_events_received_at', 'webhook_events', ['received_at'], unique=False)
    op.create_index('uq_webhook_events_provider_event', 'webhook_events', ['provider', 'provider_event_id'], unique=True)
    op.create_table('addresses',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=48), server_default='Home', nullable=False),
    sa.Column('address_type', sa.Enum('SHIPPING', 'BILLING', name='address_type'), server_default='SHIPPING', nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=24), nullable=False),
    sa.Column('line1', sa.String(length=200), nullable=False),
    sa.Column('line2', sa.String(length=200), nullable=True),
    sa.Column('landmark', sa.String(length=160), nullable=True),
    sa.Column('city', sa.String(length=96), nullable=False),
    sa.Column('state', sa.String(length=96), nullable=False),
    sa.Column('postal_code', sa.String(length=16), nullable=False),
    sa.Column('country_code', sa.String(length=2), server_default='IN', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_addresses_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses'))
    )
    op.create_index('ix_addresses_profile_id', 'addresses', ['profile_id'], unique=False)
    op.create_index('uq_addresses_one_default_per_profile', 'addresses', ['profile_id'], unique=True, postgresql_where=sa.text('is_default'))
    op.create_table('audit_logs',
    sa.Column('actor_profile_id', sa.UUID(), nullable=True),
    sa.Column('actor_label', sa.String(length=64), server_default='system', nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_profile_id'], ['profiles.id'], name=op.f('fk_audit_logs_actor_profile_id_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_actor_created', 'audit_logs', ['actor_profile_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('carts',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CONVERTED', 'ABANDONED', 'EXPIRED', name='cart_status'), server_default='ACTIVE', nullable=False),
    sa.Column('coupon_code_snapshot', sa.String(length=48), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovery_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovery_token', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_carts_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carts'))
    )
    op.create_index('ix_carts_status_updated_at', 'carts', ['status', 'updated_at'], unique=False)
    op.create_index('uq_carts_one_active_per_user', 'carts', ['profile_id'], unique=True, postgresql_where=sa.text("status IN ('ACTIVE', 'ABANDONED')"))
    op.create_table('coupons',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('coupon_type', sa.Enum('PERCENTAGE', 'FIXED', name='coupon_type'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('max_discount_amount', sa.Integer(), nullable=True),
    sa.Column('min_order_amount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('per_user_limit', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('category_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('product_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_items', sa.SmallInteger(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('per_user_limit IS NULL OR per_user_limit > 0', name=op.f('ck_coupons_per_user_limit_positive')),
    sa.CheckConstraint('usage_limit IS NULL OR usage_count < usage_limit', name=op.f('ck_coupons_usage_under_limit')),
    sa.CheckConstraint('value > 0 AND value <= 10000', name=op.f('ck_coupons_percentage_basis_points_in_range')),
    sa.ForeignKeyConstraint(['created_by'], ['profiles.id'], name=op.f('fk_coupons_created_by_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupons')),
    sa.UniqueConstraint('code', name='uq_coupons_code')
    )
    op.create_index('ix_coupons_is_active_expires_at', 'coupons', ['is_active', 'expires_at'], unique=False)
    op.create_table('newsletter_subscribers',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'UNSUBSCRIBED', 'BOUNCED', name='subscriber_status'), server_default='PENDING', nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unsubscribe_token', sa.String(length=64), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_newsletter_subscribers_profile_id_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletter_subscribers')),
    sa.UniqueConstraint('email', name='uq_newsletter_subscribers_email')
    )
    op.create_index('ix_newsletter_subscribers_status', 'newsletter_subscribers', ['status'], unique=False)
    op.create_table('orders',
    sa.Column('order_number', sa.String(length=24), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAYMENT_PENDING', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='order_status'), server_default='PENDING', nullable=False),
    sa.Column('payment_status', sa.Enum('CREATED', 'AUTHORIZED', 'CAPTURED', 'FAILED', 'REFUNDED', name='payment_status'), server_default='CREATED', nullable=False),
    sa.Column('discount_source', sa.Enum('COUPON', 'MANUAL', 'LOYALTY', name='discount_source'), nullable=True),
    sa.Column('subtotal', sa.Integer(), server_default='0', nullable=False),
    sa.Column('discount_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('shipping_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tax_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('refunded_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=24), nullable=False),
    sa.Column('shipping_name', sa.String(length=160), nullable=False),
    sa.Column('shipping_line1', sa.String(length=200), nullable=False),
    sa.Column('shipping_line2', sa.String(length=200), nullable=True),
    sa.Column('shipping_landmark', sa.String(length=160), nullable=True),
    sa.Column('shipping_city', sa.String(length=96), nullable=False),
    sa.Column('shipping_state', sa.String(length=96), nullable=False),
    sa.Column('shipping_postal_code', sa.String(length=16), nullable=False),
    sa.Column('shipping_country_code', sa.String(length=2), server_default='IN', nullable=False),
    sa.Column('billing_name', sa.String(length=160), nullable=True),
    sa.Column('billing_line1', sa.String(length=200), nullable=True),
    sa.Column('billing_line2', sa.String(length=200), nullable=True),
    sa.Column('billing_city', sa.String(length=96), nullable=True),
    sa.Column('billing_state', sa.String(length=96), nullable=True),
    sa.Column('billing_postal_code', sa.String(length=16), nullable=True),
    sa.Column('billing_country_code', sa.String(length=2), nullable=True),
    sa.Column('shipping_method', sa.Enum('STANDARD', 'EXPRESS', name='order_shipping_method'), server_default='STANDARD', nullable=False),
    sa.Column('shipping_carrier', sa.String(length=80), nullable=True),
    sa.Column('tracking_number', sa.String(length=120), nullable=True),
    sa.Column('tracking_url', sa.Text(), nullable=True),
    sa.Column('estimated_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.String(length=240), nullable=True),
    sa.Column('customer_note', sa.String(length=500), nullable=True),
    sa.Column('internal_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_total >= 0', name=op.f('ck_orders_discount_non_negative')),
    sa.CheckConstraint('shipping_total >= 0', name=op.f('ck_orders_shipping_non_negative')),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_orders_subtotal_non_negative')),
    sa.CheckConstraint('tax_total >= 0', name=op.f('ck_orders_tax_non_negative')),
    sa.CheckConstraint('total = subtotal - discount_total + shipping_total + tax_total', name=op.f('ck_orders_total_consistent')),
    sa.CheckConstraint('total >= 0', name=op.f('ck_orders_total_non_negative')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_orders_profile_id_profiles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('order_number', name='uq_orders_order_number')
    )
    op.create_index('ix_orders_email', 'orders', ['email'], unique=False)
    op.create_index('ix_orders_open_queue', 'orders', ['created_at'], unique=False, postgresql_where=sa.text("status NOT IN ('CANCELLED', 'REFUNDED', 'DELIVERED')"))
    op.create_index('ix_orders_paid_at', 'orders', ['paid_at'], unique=False, postgresql_where=sa.text("status NOT IN ('CANCELLED')"))
    op.create_index('ix_orders_profile_created', 'orders', ['profile_id', 'created_at'], unique=False)
    op.create_index('ix_orders_status_created', 'orders', ['status', 'created_at'], unique=False)
    op.create_table('products',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('subtitle', sa.String(length=240), nullable=True),
    sa.Column('short_description', sa.String(length=400), nullable=True),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('base_price', sa.BigInteger(), nullable=False),
    sa.Column('compare_at_price', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='product_status'), server_default='DRAFT', nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('seo_title', sa.String(length=180), nullable=True),
    sa.Column('seo_description', sa.String(length=320), nullable=True),
    sa.Column('seo_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('price_min', sa.BigInteger(), nullable=True),
    sa.Column('price_max', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_price >= 0', name=op.f('ck_products_base_price_non_negative')),
    sa.CheckConstraint('compare_at_price IS NULL OR compare_at_price >= base_price', name=op.f('ck_products_compare_at_above_base')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('sku', name='uq_products_sku'),
    sa.UniqueConstraint('slug', name='uq_products_slug')
    )
    op.create_index('ix_products_brand', 'products', ['brand'], unique=False)
    op.create_index('ix_products_category_id', 'products', ['category_id'], unique=False)
    op.create_index('ix_products_is_featured_status', 'products', ['is_featured', 'status'], unique=False)
    op.create_index('ix_products_listing', 'products', ['status', 'created_at'], unique=False, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_index('ix_products_search', 'products', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_products_status_created_at', 'products', ['status', 'created_at'], unique=False)
    op.create_table('user_sessions',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_user_sessions_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_sessions_token_hash'))
    )
    op.create_index('ix_user_sessions_last_seen', 'user_sessions', ['last_seen_at'], unique=False)
    op.create_index('ix_user_sessions_profile_started', 'user_sessions', ['profile_id', 'started_at'], unique=False)
    op.create_table('wishlists',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_wishlists_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wishlists')),
    sa.UniqueConstraint('profile_id', name='uq_wishlists_profile_id')
    )
    op.create_table('coupon_usages',
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('discount_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name=op.f('fk_coupon_usages_coupon_id_coupons'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_coupon_usages_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_coupon_usages_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coupon_usages')),
    sa.UniqueConstraint('order_id', name='uq_coupon_usages_order_id')
    )
    op.create_index('ix_coupon_usages_coupon_profile', 'coupon_usages', ['coupon_id', 'profile_id'], unique=False)
    op.create_table('email_logs',
    sa.Column('kind', sa.Enum('WELCOME', 'EMAIL_VERIFICATION', 'PASSWORD_RESET', 'ORDER_CONFIRMATION', 'PAYMENT_CONFIRMATION', 'PAYMENT_FAILED', 'SHIPPING_UPDATE', 'DELIVERY_CONFIRMATION', 'ORDER_CANCELLED', 'REFUND_ISSUED', 'ABANDONED_CART', 'LOW_STOCK_ALERT', 'NEWSLETTER_WELCOME', name='email_kind'), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=240), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_message_id', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_email_logs_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_email_logs_profile_id_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_logs'))
    )
    op.create_index('ix_email_logs_kind_created', 'email_logs', ['kind', 'created_at'], unique=False)
    op.create_index('ix_email_logs_recipient', 'email_logs', ['recipient'], unique=False)
    op.create_table('order_events',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('PENDING', 'PAYMENT_PENDING', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='order_status'), nullable=True),
    sa.Column('to_status', sa.Enum('PENDING', 'PAYMENT_PENDING', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='order_status'), nullable=False),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.Column('actor_profile_id', sa.UUID(), nullable=True),
    sa.Column('is_customer_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_profile_id'], ['profiles.id'], name=op.f('fk_order_events_actor_profile_id_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_events_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_events'))
    )
    op.create_index('ix_order_events_order_created', 'order_events', ['order_id', 'created_at'], unique=False)
    op.create_table('payments',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('RAZORPAY', name='payment_provider'), server_default='RAZORPAY', nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'AUTHORIZED', 'CAPTURED', 'FAILED', 'REFUNDED', name='payment_status'), server_default='CREATED', nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=128), nullable=True),
    sa.Column('method', sa.String(length=48), nullable=True),
    sa.Column('bank', sa.String(length=96), nullable=True),
    sa.Column('gateway_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('failure_code', sa.String(length=96), nullable=True),
    sa.Column('failure_reason', sa.String(length=400), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payments_amount_positive')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payments_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('razorpay_order_id', name='uq_payments_razorpay_order_id'),
    sa.UniqueConstraint('razorpay_payment_id', name='uq_payments_razorpay_payment_id')
    )
    op.create_index('ix_payments_created_at', 'payments', ['created_at'], unique=False)
    op.create_index('ix_payments_order_id', 'payments', ['order_id'], unique=False)
    op.create_index('ix_payments_status', 'payments', ['status'], unique=False)
    op.create_table('product_images',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('alt_text', sa.String(length=200), server_default='', nullable=False),
    sa.Column('position', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('blur_data_url', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_images_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_images'))
    )
    op.create_index('ix_product_images_product_id_position', 'product_images', ['product_id', 'position'], unique=False)
    op.create_index('uq_product_images_one_primary', 'product_images', ['product_id'], unique=True, postgresql_where=sa.text('is_primary'))
    op.create_table('product_rating_summaries',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('average_rating', sa.Float(), server_default='0', nullable=False, comment='Rounded to 2dp on write'),
    sa.Column('review_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('distribution', postgresql.ARRAY(sa.Integer()), server_default='{}', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_rating_summaries_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_product_rating_summaries'))
    )
    op.create_table('product_tags',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_tags_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_product_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'tag_id', name=op.f('pk_product_tags'))
    )
    op.create_index('ix_product_tags_tag_id', 'product_tags', ['tag_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('price_override', sa.BigInteger(), nullable=True),
    sa.Column('compare_at_price', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'OUT_OF_STOCK', 'DISCONTINUED', name='variant_status'), server_default='ACTIVE', nullable=False),
    sa.Column('position', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), server_default='3', nullable=False),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_override IS NULL OR price_override >= 0', name=op.f('ck_product_variants_price_non_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_variants_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_variants')),
    sa.UniqueConstraint('sku', name='uq_product_variants_sku')
    )
    op.create_index('ix_product_variants_product_id', 'product_variants', ['product_id'], unique=False)
    op.create_index('ix_product_variants_product_id_status', 'product_variants', ['product_id', 'status'], unique=False)
    op.create_index('ix_product_variants_sku_lookup', 'product_variants', ['sku'], unique=True)
    op.create_table('cart_items',
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('added_from', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity <= 99', name=op.f('ck_cart_items_quantity_max_99')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_cart_items_quantity_positive')),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name=op.f('fk_cart_items_cart_id_carts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_cart_items_variant_id_product_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart_items')),
    sa.UniqueConstraint('cart_id', 'variant_id', name='uq_cart_items_cart_variant')
    )
    op.create_index('ix_cart_items_cart_id', 'cart_items', ['cart_id'], unique=False)
    op.create_index('ix_cart_items_variant_id', 'cart_items', ['variant_id'], unique=False)
    op.create_table('inventory',
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reserved', sa.Integer(), server_default='0', nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), server_default='3', nullable=False),
    sa.Column('reorder_point', sa.Integer(), server_default='5', nullable=False),
    sa.Column('available', sa.Integer(), sa.Computed('quantity - reserved', persisted=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_inventory_quantity_non_negative')),
    sa.CheckConstraint('reserved <= quantity', name=op.f('ck_inventory_reserved_not_over_quantity')),
    sa.CheckConstraint('reserved >= 0', name=op.f('ck_inventory_reserved_non_negative')),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_inventory_variant_id_product_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory')),
    sa.UniqueConstraint('variant_id', name=op.f('uq_inventory_variant_id'))
    )
    op.create_index('ix_inventory_low_stock', 'inventory', ['low_stock_threshold'], unique=False)
    op.create_index('ix_inventory_variant_id', 'inventory', ['variant_id'], unique=True)
    op.create_table('inventory_movements',
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('reserved_delta', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reason', sa.Enum('RESTOCK', 'SALE', 'RESERVATION', 'RELEASE', 'RETURN', 'ADJUSTMENT', 'DAMAGE', name='inventory_reason'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(length=240), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_inventory_movements_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_inventory_movements_variant_id_product_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_movements'))
    )
    op.create_index('ix_inventory_movements_order_id', 'inventory_movements', ['order_id'], unique=False)
    op.create_index('ix_inventory_movements_variant_created', 'inventory_movements', ['variant_id', 'created_at'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('variant_title', sa.String(length=160), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('compare_at_price', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.SmallInteger(), nullable=False),
    sa.Column('line_discount', sa.Integer(), server_default='0', nullable=False, comment='Per-line share of the coupon discount, for accurate refund maths'),
    sa.Column('line_tax', sa.Integer(), server_default='0', nullable=False, comment='Tax attributed to this line'),
    sa.Column('total', sa.Integer(), nullable=False, comment='unit_price * quantity - line_discount + line_tax'),
    sa.Column('refunded_quantity', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('position', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_items_quantity_positive')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_order_items_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_items_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_order_items_variant_id_product_variants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_index('ix_order_items_product_id', 'order_items', ['product_id'], unique=False)
    op.create_index('ix_order_items_variant_id', 'order_items', ['variant_id'], unique=False)
    op.create_table('refunds',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=240), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSED', 'FAILED', name='refund_status'), server_default='PENDING', nullable=False),
    sa.Column('razorpay_refund_id', sa.String(length=64), nullable=True),
    sa.Column('restock', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=400), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_refunds_amount_positive')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_refunds_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_refunds_payment_id_payments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by'], ['profiles.id'], name=op.f('fk_refunds_requested_by_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds')),
    sa.UniqueConstraint('razorpay_refund_id', name='uq_refunds_razorpay_refund_id')
    )
    op.create_index('ix_refunds_order_id', 'refunds', ['order_id'], unique=False)
    op.create_table('reviews',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='review_status'), server_default='PENDING', nullable=False),
    sa.Column('verified_purchase', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('moderated_by', sa.UUID(), nullable=True),
    sa.Column('moderation_note', sa.String(length=400), nullable=True),
    sa.Column('helpful_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(comment) BETWEEN 1 AND 4000', name=op.f('ck_reviews_comment_length')),
    sa.CheckConstraint('char_length(title) BETWEEN 1 AND 140', name=op.f('ck_reviews_title_length')),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('ck_reviews_rating_between_1_and_5')),
    sa.ForeignKeyConstraint(['moderated_by'], ['profiles.id'], name=op.f('fk_reviews_moderated_by_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_reviews_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_reviews_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_reviews_profile_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_reviews_variant_id_product_variants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('product_id', 'profile_id', name='uq_reviews_product_profile')
    )
    op.create_index('ix_reviews_product_status_created', 'reviews', ['product_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_reviews_status', 'reviews', ['status'], unique=False)
    op.create_table('stock_notifications',
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_stock_notifications_profile_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_stock_notifications_variant_id_product_variants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_notifications'))
    )
    op.create_index('uq_stock_notifications_variant_profile', 'stock_notifications', ['variant_id', 'profile_id'], unique=True)
    op.create_table('wishlist_items',
    sa.Column('wishlist_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('notify_on_restock', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_wishlist_items_variant_id_product_variants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], name=op.f('fk_wishlist_items_wishlist_id_wishlists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wishlist_items')),
    sa.UniqueConstraint('wishlist_id', 'variant_id', name='uq_wishlist_items_wishlist_variant')
    )
    op.create_index('ix_wishlist_items_wishlist_id', 'wishlist_items', ['wishlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wishlist_items_wishlist_id', table_name='wishlist_items')
    op.drop_table('wishlist_items')
    op.drop_index('uq_stock_notifications_variant_profile', table_name='stock_notifications')
    op.drop_table('stock_notifications')
    op.drop_index('ix_reviews_status', table_name='reviews')
    op.drop_index('ix_reviews_product_status_created', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_refunds_order_id', table_name='refunds')
    op.drop_table('refunds')
    op.drop_index('ix_order_items_variant_id', table_name='order_items')
    op.drop_index('ix_order_items_product_id', table_name='order_items')
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_inventory_movements_variant_created', table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_order_id', table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index('ix_inventory_variant_id', table_name='inventory')
    op.drop_index('ix_inventory_low_stock', table_name='inventory')
    op.drop_table('inventory')
    op.drop_index('ix_cart_items_variant_id', table_name='cart_items')
    op.drop_index('ix_cart_items_cart_id', table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index('ix_product_variants_sku_lookup', table_name='product_variants')
    op.drop_index('ix_product_variants_product_id_status', table_name='product_variants')
    op.drop_index('ix_product_variants_product_id', table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index('ix_product_tags_tag_id', table_name='product_tags')
    op.drop_table('product_tags')
    op.drop_table('product_rating_summaries')
    op.drop_index('uq_product_images_one_primary', table_name='product_images', postgresql_where=sa.text('is_primary'))
    op.drop_index('ix_product_images_product_id_position', table_name='product_images')
    op.drop_table('product_images')
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_index('ix_payments_order_id', table_name='payments')
    op.drop_index('ix_payments_created_at', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_order_events_order_created', table_name='order_events')
    op.drop_table('order_events')
    op.drop_index('ix_email_logs_recipient', table_name='email_logs')
    op.drop_index('ix_email_logs_kind_created', table_name='email_logs')
    op.drop_table('email_logs')
    op.drop_index('ix_coupon_usages_coupon_profile', table_name='coupon_usages')
    op.drop_table('coupon_usages')
    op.drop_table('wishlists')
    op.drop_index('ix_user_sessions_profile_started', table_name='user_sessions')
    op.drop_index('ix_user_sessions_last_seen', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_products_status_created_at', table_name='products')
    op.drop_index('ix_products_search', table_name='products', postgresql_using='gin')
    op.drop_index('ix_products_listing', table_name='products', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('ix_products_is_featured_status', table_name='products')
    op.drop_index('ix_products_category_id', table_name='products')
    op.drop_index('ix_products_brand', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_orders_status_created', table_name='orders')
    op.drop_index('ix_orders_profile_created', table_name='orders')
    op.drop_index('ix_orders_paid_at', table_name='orders', postgresql_where=sa.text("status NOT IN ('CANCELLED')"))
    op.drop_index('ix_orders_open_queue', table_name='orders', postgresql_where=sa.text("status NOT IN ('CANCELLED', 'REFUNDED', 'DELIVERED')"))
    op.drop_index('ix_orders_email', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_newsletter_subscribers_status', table_name='newsletter_subscribers')
    op.drop_table('newsletter_subscribers')
    op.drop_index('ix_coupons_is_active_expires_at', table_name='coupons')
    op.drop_table('coupons')
    op.drop_index('uq_carts_one_active_per_user', table_name='carts', postgresql_where=sa.text("status IN ('ACTIVE', 'ABANDONED')"))
    op.drop_index('ix_carts_status_updated_at', table_name='carts')
    op.drop_table('carts')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_addresses_one_default_per_profile', table_name='addresses', postgresql_where=sa.text('is_default'))
    op.drop_index('ix_addresses_profile_id', table_name='addresses')
    op.drop_table('addresses')
    op.drop_index('uq_webhook_events_provider_event', table_name='webhook_events')
    op.drop_index('ix_webhook_events_received_at', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_table('tags')
    op.drop_table('shipping_methods')
    op.drop_index('ix_profiles_role', table_name='profiles')
    op.drop_index('ix_profiles_created_at', table_name='profiles')
    op.drop_table('profiles')
    op.drop_index('ix_outbox_events_status_created', table_name='outbox_events')
    op.drop_index('ix_outbox_events_dedupe_key', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index('uq_idempotency_keys_scope_key', table_name='idempotency_keys')
    op.drop_index('ix_idempotency_keys_expires_at', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_table('id_counters')
    op.drop_index('ix_categories_parent_id', table_name='categories')
    op.drop_index('ix_categories_is_active_position', table_name='categories')
    op.drop_table('categories')
    op.drop_table('analytics_daily')
    # ### end Alembic commands ###

    # PostgreSQL does not drop an enum type when a table that uses it is
    # dropped, and Alembic's autogenerated downgrade does not emit DROP TYPE.
    # Without this, `downgrade base` followed by `upgrade head` fails with
    # "type ... already exists", which would make the documented rollback
    # strategy unusable exactly when it is needed most.
    #
    # These run only after every table above is gone, and deliberately without
    # CASCADE so a type still referenced by an unexpected object fails loudly
    # instead of silently taking that object with it.
    for enum_type in _ENUM_TYPES:
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_type}"))
